# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f9015f83c638784cd23f5b9707b35b3d3ec3b3335cdfa3ff80b7da8bac78f6f8719cb1fe3924fa6b752642e0e3fef1b69c7ca9fe37d2a1588942aa07b4c8e11

test:
  secret_key_base: 083114a49f5c8be2abd81f85b9df09a55f893a728f0b4612c512d1db9ffc2f802b42e042fcb3b7564a0b66105ec7fdf145e767538f05a95ad884e235a7dd5423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
